project: 
  type: website
  #output-dir: _site
  output-dir: doc
  

website: 
  title: "Ipshita (SORTEE Code Club)"
  
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
     
    right: 
      - icon: github
      - href: https://github.com/Ipshita7
      
  page-footer: 
    center: "Build with [Quarto](https://quarto.org/)"
    
format: 
  html:
    theme: flatly
    toc: true
  
    
    
    
    
    
    
